### ISSUE TITLE
Best practices for partial async implementation in DRF

### ISSUE THREAD

**Issue by gschurck** [hisdream86/drf-async-view#8]
I have currently a Django API project built with DRF.
I would like to use async for some endpoints to optimize long API calls.
What are the best practices in terms of performance ?
I suppose that I have to change my server for Uvicorn ?
Will the normal sync views still work correctly ?
Thanks.

**Comment by hisdream86** [comment]
Basically, the asynchronous framework is practical if
- Most of your APIs are IO-bounded
- You want to improve the total throughput (ex. RPS) of your server

In this case, you can improve the performance using asyncio, unicorn, and so on.

---

However, I think you want to optimize **a single slow endpoint**.

In this case, you need to find WHAT makes your API slow. before you optimize a slow API.

### (1) If your slow API consists of CPU-intensive tasks, the asyncio can't help you
You need to optimize your source code. Or, you can separate your task into several sub-tasks and run these in parallel using multi-thread

### (2) If your API is slow because of a single slow I/O task, the asyncio can't help you
You should optimize your I/O task (ex. Optimize your query)

### (2) If your slow API consists of several I/O tasks, the asyncio can help you
Let me assume your slow API likes below.
```python
def io_task_1():
    db.query("SELECT ...") # Takes 1 second

def io_task_2():
    db.query("SELECT ...") # Takes 2 second

def slow_api():
    io_task_1()
    io_task_2()
    # Takes 3 second
```

You can make your I/O tasks into asynchronous tasks. 
However, it's insufficient because `io_task_2()` is still waiting for the end of `io_task_1()`.
```python
async def io_task_1():
    await db.async_query("SELECT ...")  # Takes 1 second

async def io_task_2():
    await db.async_query("SELECT ...")  # Takes 2 second

async def slow_api():
    await io_task_1()
    await io_task_2()
    # Takes 3 second
```

So, you can makes your I/O tasks runs concurrently using `asyncio.gather()`
```python
async def io_task_1():
    await db.async_query("SELECT ...")  # Takes 1 second

async def io_task_2():
    await db.async_query("SELECT ...")  # Takes 2 second

async def slow_api():
    await asyncio.gather(io_task_1(), io_task_2())
    # Takes 2 second
```

**Comment by gschurck** [comment]
Thanks for your answer.
For my case my API consists of several slow I/O tasks,but it's more like each user make one long external API call, so I can't combine them manually using asyncio.gather() directly.
But asyncio can still help improving performances for several users with a blocking I/O, right ? Or I misunderstood it.

**Comment by hisdream86** [comment]
> Thanks for your answer.
> For my case my API consists of several slow I/O tasks,but it's more like each user make one long external API call, so I can't combine them manually using asyncio.gather() directly.
> But asyncio can still help improving performances for several users with a blocking I/O, right ? Or I misunderstood it.

In this case, you can improve the throughput of your API server under the same CPU resources if you apply async frameworks (ex. uvicorn + async view) because your APIs are I/O bound.
- You would process more requests compared with multi-threading ways. (ex. uwsgi, gunicon-gthread, ...)
- Note that high throughput != low response time

However, you can't reduce the response time for each slow API. You need to optimize your slow I/O task.

**Comment by gschurck** [comment]
Yes, so I need to use uvicorn with async views.
But how will Django + DRF work for all the rest that is still sync, on an uvicorn server ? Are there any issues with this kind of setup ?

**Comment by hisdream86** [comment]
Synchronous code lines work synchronously even if you run codes inside the async context.

```python
async my_function():
    something_to_do() # Working synchronously
    await awaitable_io_task() # Working synchronously
```

So, **the first thing you have to do** is update your I/O code blocks to the async-based. Some python packages provide these features.
- `aiohttp`, `aioboto3`, `aiomysql`, ...

After updating your I/O code blocks asynchronously, It will be required to define the API views using the async function. [Django 4.1](https://docs.djangoproject.com/en/4.1/topics/async/#async-views) supports this.
- However, DRF doesn't support this yet.
- So, you can use [this package](https://github.com/hisdream86/drf-async-view) if you want to define async views in DRF.

Finally, you need to run your server behind the asgi server (ex. uvicorn) to handle requests asynchronously.

**Comment by gschurck** [comment]
Okay so I can run both async and sync views without issues on uvicorn, the best of both worlds.
That's a shame that DRF doesn't plan to support async natively today.
Thank you, I will try your package.
